info:
  title: FCP SFD Data API
  version: 0.0.1
  description: API for FCP Single Front Door Data service
  contact:
    name: SFD Devs
    url: https://github.com/orgs/DEFRA/teams/fcp-sfd-devs
servers:
  - url: http://localhost:3000
    description: local server
tags:
  - name: health
    description: Health check endpoint
  - name: comms
    description: Operations supporting the SFD communications service
  - name: object
    description: Operations supporting the SFD object processing service
openapi: 3.0.0
components:
  schemas: {}
paths:
  /health:
    get:
      operationId: getHealth
      tags:
        - health
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
  /comms/events/id/{id}:
    get:
      operationId: getCommsEventsIdId
      parameters:
        - name: id
          in: path
          schema:
            type: string
            x-format:
              guid:
                version: uuidv4
          required: true
      tags:
        - comms
      responses:
        default:
          description: Successful
          content:
            application/json:
              schema:
                type: string
